# Generated by Django 4.0.7 on 2022-08-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='related',
        ),
        migrations.AddField(
            model_name='blog',
            name='related_posts',
            field=models.ManyToManyField(to='blog.blog'),
        ),
    ]
